language: java
jdk:
  - openjdk14
sudo: false
env:
install: true
script: mvn clean package -DskipTests=true
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients: "-nikich85@inbox.ru"
    on_success: never
    on_failure: always
